name: 测试

on:
  #schedule:
    #- cron: '10 */6 * * *'        #这里更改自动运行的时间，没这两行的话只能手动运行
  workflow_dispatch:
    分支:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
         run: pip install selenium requests futures eventlet
         run: pip install opencv-python requests
         run: pip install Beautifulsoup4 requests
         run: pip install translate requests
         run: pip install ffmpy
         run: pip install termcolor
         run: pip install func_timeout
         run: pip install replace
         run: pip install input
         run: pip install opencc
         run: pip install pypinyin
         run: pip install pytz  
      - name: Run iptv
        run: python ${{ github.workspace }}/组播py/iptv_udp.py     #这里更改要运行的py
      
        

      - name: 提交更改
        run: |
          git config --local user.email "actions@126.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
